services:
  - type: web
    name: quizzzzzz
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
